### ISSUE TITLE
Implied multiplication with unexpected results

### ISSUE THREAD

**Issue by BuddyDeveloping** [bradhowes/swift-math-parser#4]
I have enabled implied multiplication and tried to calculate "parser.parse('6÷2(1+2)').eval()". The solution given is "6".

I am not sure how this value is achieved or if I'm missing something.

<img width="337" alt="Screenshot 2023-07-11 at 3 49 48 pm" src="https://github.com/bradhowes/swift-math-parser/assets/116281350/8d777534-1ff0-404a-b76a-ea89dd693d3b">

**Comment by bradhowes** [comment]
Clearly a bug. I'll add it as a test and see what is going on. Thanks!

**Comment by bradhowes** [comment]
I have updated the code to disable the implied multiplication feature until it is fixed.

**Comment by bradhowes** [comment]
I have updated the code to fix your issue and others. Note that there can be unexpected parsing results if operators are not separated by spaces and you are enabling implied multiplication. For instance, while your `6/2(1+2)` works now to give `9`, the expression `6/2(1-2)` does _not_ give `-3` but rather `-6` because `1-2` is treated as two tokens (1, -2) instead of 3.
