### ISSUE TITLE
Factorial presents crash on returned nonpositive

### ISSUE THREAD

**Issue by BuddyDeveloping** [bradhowes/swift-math-parser#5]
I am testing the new factorial feature and for some or other reason anything that is not just a number (brackets and functions) produces an error if it is negative or zero. For example "(5x-6)!", "cos(π)!", "sin(4)!". Please note I have implied multiplication enabled.

Also I'm not sure if this is intended but when implied multiplication is enabled, the "!" has to be directly after a number/group instead of with a space. 

Finally, I'm curious as to why the implied multiplication is set up to need spaces? Is there a way to have it without need to makes spaces as it seems to case a lot of different test cases with normal use.

Thanks for your time,
Chris
BuddyDeveloping

**Comment by bradhowes** [comment]
Hi Chris,

The parsing that is there is just to serve my needs. You can of course adapt it to your own by forking it and making it your own. One that is fairly easy to do is to insert an optional space parser (called ignoreSpaces) before the Optionally("!”) parser.

> Finally, I'm curious as to why the implied multiplication is set up to need spaces? Is there a way to have it without need to makes spaces as it seems to case a lot of different test cases with normal use.
> 

The real reason is because I did not want to rework the parsers to better support implied multiplication and the ambiguity that exists between recognizing a subtraction and a multiplication with a negative number. For my use case, I don’t have any problem with the spacing, and it all works as I need it to.

Again, experiment with the code and you may be able to arrive at something the does what you want. Unfortunately, it can be tricky to get the parsers to do what you want and to get Swift to tell you a meaningful error message when you get the types wrong. But I strongly recommend that you try cloning the project, checking it out locally on your programming device, and then adding your local clone as a local package to whatever project you are working on. That way you can experiment and try it out without having to depend on my Github sources.

Regards,

Brad
